version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./wait-for-it/wait-for-it.sh db:3306 --timeout=30 --strict -- ./wait-for-it/wait-for-it.sh redis:6379 --timeout=30 --strict -- pnpm start
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=test
      - DB_DATABASE=task_manager
      - DB_PORT=3306
      - PORT=8080

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=task_manager
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
